### ISSUE TITLE
Can't get autocomplete to work

### ISSUE THREAD

**Issue by MisterSpicy** [coronalabs/CoronaSDK-AtomPlugin#8]
Hello!

I've stumbled out of the gate - I have a clean install of Atom, as well as Corona SDK.  I installed language-lua and the autocomplete-corona packages, then created a new Corona project, added in main.lua "local title = display. " and get no autocomplete.

Looking around the forums seems that it works for most people?  I'm wondering if I'm missing a required step?

Thanks!

**Comment by erikhm91** [comment]
Hi, I have the same issue. 
Hope you can share if you have found the solution somewhere else!

**Comment by ghost** [comment]
Faced the same problem. Previously, everything was fine, but after such as reinstalling Windows more in Atom, autocomplete does not work. I'm writing at the moment in Sublime Text

**Comment by ghost** [comment]
While looking for what the problem will say that if you roll back to the previous version (v.1.1.3) everything will work here link https://github.com/coronalabs/CoronaSDK-AtomPlugin/releases/tag/v1.1.3

**Comment by ghost** [comment]
In version 1.1.4, the syntax for which the plugin will work on this is not specified; you need to go to the plug-in folder for Atom and find the plug-in folder "autocomplete-corona" and find the "main.coffe" file in the lib folder ( C:\Users\USERNAME/.atom\packages\autocomplete-corona\lib) and in this file, change the line "packageDeps.install()" to "packageDeps.install('language-lua')"

**Comment by TJSchmitz** [comment]
Thanks @what228, your solution worked flawlessly!

**Comment by phutai88** [comment]
> In version 1.1.4, the syntax for which the plugin will work on this is not specified; you need to go to the plug-in folder for Atom and find the plug-in folder "autocomplete-corona" and find the "main.coffe" file in the lib folder ( C:\Users\USERNAME/.atom\packages\autocomplete-corona\lib) and in this file, change the line "packageDeps.install()" to "packageDeps.install('language-lua')"

It worked. Thank you very much.

**Comment by Shchvova** [comment]
This should be fixed in latest release.

**Comment by edge1** [comment]
It's still not working.
